# Generated by Django 4.2.7 on 2023-11-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=55, verbose_name="O'quv xonasi"),
        ),
    ]
