# Generated by Django 4.2.7 on 2023-11-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_botuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='kurs',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, verbose_name='Kurs'),
            preserve_default=False,
        ),
    ]
