# Generated by Django 4.2.7 on 2023-11-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_botuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='user_full_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User full name'),
        ),
    ]
