# Generated by Django 4.2.7 on 2023-11-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_botuser_user_full_name'),
        ('schedule', '0005_group_kurs'),
    ]

    operations = [
    ]
