# Generated by Django 4.2.7 on 2023-11-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_merge_0005_botuser_user_full_name_0005_group_kurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.FileField(upload_to='documents/', verbose_name='Fayl url'),
        ),
    ]
