# Generated by Django 4.2.7 on 2023-11-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_document_file_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='number',
            new_name='room',
        ),
        migrations.AddField(
            model_name='schedule',
            name='lesson_type',
            field=models.CharField(choices=[('Amaliyot', 'Amaliyot'), ("Maru'za", "Maru'za"), ('Laboratoriya', 'Laboratoriya')], default='Amaliyot', max_length=50, verbose_name='Dars turi'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='week',
            field=models.CharField(choices=[('full', 'full'), ('odd', 'odd'), ('even', 'even')], default='full', max_length=20, verbose_name='Hafta'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.FileField(upload_to='documents/', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='group',
            name='academic_code',
            field=models.CharField(max_length=50, verbose_name='Guruh code'),
        ),
        migrations.AlterField(
            model_name='group',
            name='kurs',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Amaliyot', 'Amaliyot'), ("Maru'za", "Maru'za"), ('Laboratoriya', 'Laboratoriya')], default='Amaliyot', max_length=50, verbose_name='Xona turi'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Dushanba', 'Dushanba'), ('Seshanba', 'Seshanba'), ('Chorshanba', 'Chorshanba'), ('Payshanba', 'Payshanba'), ('Juma', 'Juma')], default='Dushanba', max_length=50, verbose_name='Kun'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='para',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=50, verbose_name='Juftlik'),
        ),
    ]
