# Generated by Django 4.2.7 on 2023-11-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_alter_document_options_document_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Amaliyot', 'Amaliyot'), ("Ma'ruza", "Ma'ruza"), ('Laboratoriya', 'Laboratoriya')], default='Amaliyot', max_length=50, verbose_name='Xona turi'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lesson_type',
            field=models.CharField(choices=[('Amaliyot', 'Amaliyot'), ("Ma'ruza", "Ma'ruza"), ('Laboratoriya', 'Laboratoriya')], default='Amaliyot', max_length=50, verbose_name='Dars turi'),
        ),
    ]
