# Generated by Django 4.2.7 on 2023-11-29 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_alter_room_room_type_alter_schedule_lesson_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Para',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('para', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='1', max_length=50, verbose_name='Juftlik')),
                ('time_start', models.TimeField(default='08:30:00', verbose_name='Juftlik boshlanish vaqti')),
                ('time_end', models.TimeField(default='09:50:00', verbose_name='Juftlik tugash vaqti')),
            ],
            options={
                'verbose_name': 'Juftlik',
                'verbose_name_plural': 'Juftliklar',
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=20, verbose_name='Semestr'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.teacher', verbose_name="O'qituvchi"),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='para',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.para', verbose_name='Juftlik'),
        ),
    ]
