# Generated by Django 4.2.7 on 2023-11-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_para_schedule_semester_alter_schedule_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='semester',
            field=models.CharField(choices=[('1', 'Kuzgi'), ('2', 'Bahorgi')], default='1', max_length=20, verbose_name='Semestr'),
        ),
    ]
